version: '3'

networks:
  traefik:
    name: traefik
    driver: bridge
  backend:
    name: backend
    driver: bridge

services:
  openapi:
    image: registry.jahiduls.mint/swaggerapi/swagger-ui:latest
    container_name: eventstore-openapi
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - BASE_URL=/explore
      - SWAGGER_JSON=/var/specs/event-store.yaml
    volumes:
      - ./spec:/var/specs:ro
    expose:
      - 8080
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.event-store-openapi.rule=Host(`eventstore.jahiduls.mint`) && PathPrefix(`/explore`)
      - traefik.http.routers.event-store-openapi.entrypoints=websecure
      - traefik.http.routers.event-store-openapi.tls=true
      - traefik.http.routers.event-store-openapi.service=event-store-openapi@docker
      - traefik.http.routers.event-store-openapi-http.rule=Host(`eventstore.jahiduls.mint`) && PathPrefix(`/explore`)
      - traefik.http.routers.event-store-openapi-http.entrypoints=web
      # Defined by traefik container
      - traefik.http.routers.event-store-openapi-http.middlewares=https-redirect
      - traefik.http.services.event-store-openapi.loadbalancer.server.port=8080

  eventstore:
    image: registry.jahiduls.mint/eventstore:${POSTGRES_VERSION}-${MESSAGE_DB_VERSION}
    build:
      context: ./database/
      dockerfile: Dockerfile
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
        - MESSAGE_DB_VERSION=${MESSAGE_DB_VERSION}
    container_name: eventstore
    restart: unless-stopped
    volumes:
      - /data/docker/eventstore/data/pgdata:/bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRES_VERSION=${POSTGRES_VERSION}
      - MESSAGE_DB_VERSION=${MESSAGE_DB_VERSION}
    networks:
      - backend
    expose:
      - 5432

