openapi: 3.0.2

info:
  title: EventStore API
  description: Backend service for the Event Store
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000/
    description: Development Server
  - url: https://eventstore.jahiduls.mint/api/
    description: Docker Server
  - url: https://eventstore.jahiduls.kube/api/
    description: Kubernetes Server

tags:
  - name: health
    description: Health APIs
  - name: write
    description: Write APIs
  - name: read
    description: Read APIs
  - name: v1
    description: V1 APIs

paths:
  /ping:
    get:
      description: Health check
      operationId: healthCheck
      tags:
        - health
      responses:
        "200":
          $ref: "#/components/responses/PingResponse"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"
  /deep-ping:
    get:
      description: Deep health check
      operationId: deepHealthCheck
      tags:
        - health
      responses:
        "200":
          $ref: "#/components/responses/PingResponse"
        "503":
          $ref: "#/components/responses/ServiceUnavailable"

  /v1/write:
    post:
      description: Write a message to a stream
      operationId: write
      tags:
        - write
        - v1
      parameters:
        - $ref: "#/components/parameters/ClientId"
      requestBody:
        $ref: "#/components/requestBodies/WriteRequest"
      responses:
        "202":
          $ref: "#/components/responses/Accepted"
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /v1/read/{streamName}:
    get:
      description: Read all the events from a stream
      operationId: read
      tags:
        - read
        - v1
      parameters:
        - $ref: "#/components/parameters/StreamName"
        - $ref: "#/components/parameters/ClientId"
        # TODO: add start index, count of messages
      responses:
        "200":
          $ref: "#/components/responses/ReadResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /v1/last/{streamName}:
    get:
      description: Read the last message from a stream
      operationId: readLastMessage
      tags:
        - read
        - v1
      parameters:
        - $ref: "#/components/parameters/StreamName"
        - $ref: "#/components/parameters/ClientId"
      responses:
        "200":
          $ref: "#/components/responses/LastResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalServerError"

components:
  parameters:
    StreamName:
      name: streamName
      in: path
      required: true
      schema:
        type: string
      example: client-explorer
    ClientId:
      name: x-evs-client-id
      in: header
      required: true
      schema:
        type: string
      example: explorer

  requestBodies:
    WriteRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"

  responses:
    Created:
      description: Created
    Accepted:
      description: Accepted
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
    LastResponse:
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Message"
    ReadResponse:
      description: Success
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Message"
    InternalServerError:
      description: Internal Server Error
    NoContent:
      description: No Content
    NotFound:
      description: Not Found
    PingResponse:
      description: Success
      content:
        text/plain:
          schema:
            type: string
    ServiceUnavailable:
      description: Service Unavailable
    Success:
      description: OK

  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        code:
          type: number
          format: int32
        message:
          type: string
    Message:
      type: object
      required:
        - id
        - type
        - streamName
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          example: ExplorerTest
        streamName:
          type: string
          example: client-explorer
        data:
          type: object
        metadata:
          type: object
